# Site settings
title: KEO Studio Photography in Melbourne - by Svetlana Pelin
description: > 
  A talanted commercial photographer in Melbourne.
baseurl: 
url: 

# Build settings
markdown: kramdown

highlighter: rouge

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
